# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Basic Info
name: Gwendolyn Ye
email: xxx@email.com
phone: (279) XXX-XXXX
location: Sacramento, CA
website: https://your-website.com
darkmode: true

# Content Sections
content:

  - title: About Me
    layout: text
    content: |
      ![My Photo](assets/img/Gwendolyn_Ye.jpg)

      I am a Sophomore at BYU, a pre-business student. I enjoy cooking traditional Chinese dishes, baking desserts, watching shows, and teaching/translation. I have experience translating for my local church and teaching English to foreign students.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Translator
        sub_title: Translating
        caption: June 2021 - August 2024
        description: |
          Spent 4 years of High School translating in my local church for the Chinese section. Fluent in Mandarin and Cantonese.

      - layout: left
        title: Link Crew Member
        sub_title: Franklin High School
        caption: August 2022 - August 2023
        description: |
          Hosted Freshman Orientation, Winter Home Coming, and Winter Tailgate events.

      - layout: left
        title: Filipino Club Historian
        sub_title: Franklin High School
        caption: August 2023 - August 2024
        description: |
          Historian for the Filipino Club in High School; advertised events on Instagram.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Franklin High School
        sub_title: High School Diploma
        caption: August 2020 - May 2024
        description: |
          GPA: 4.10

  - title: Skills
    layout: text
    content: |
      - Fluent in speaking Mandarin, Cantonese, and English
      - Intermediate knowledge in Microsoft Word, Excel, and PowerPoint
      - Honors Program experience; able to plan activities

  - title: Interests
    layout: text
    content: |
      I enjoy cooking traditional Chinese dishes, baking desserts, editing clips, crocheting, and good communications.

  - title: Awards & Certifications
    layout: list
    content:
      - layout: left
        title: Outstanding Academic Excellence
        caption: 2024

      - layout: left
        title: California State Seal of Biliteracy Recognition
        caption: 2024

  - title: Fun Projects
    layout: text
    content: |
      Check out my interactive Chinese Food guessing game: [Play here](scratchpg.html)
      ![Dumplings Game](assets/img/Dumplings.jpg)
